### ISSUE TITLE
Mail send info like success or not issue.

### ISSUE THREAD

**Issue by smithHK** [agence-webup/laravel-sendinblue#13]
Hi,
    How can i check to Mail::raw() mail actually send or not. So here send mail nothing return anything. so i does not known about mail actually send or not. or nothing return any thing error related to bounce mail etc.

Please help me about that.
Thank you.

**Comment by Biptaste** [comment]
Hi,
You can catch the exception Webup\LaravelSendinBlue\SendinBlueException. I throw it if the Sendinblue API send an error.

**Comment by bionimic** [comment]
I have tried it. still and issue.

try {
	$strEmail = $this->argument('email');
	Mail::send('emails.test', [], function ($message) use ($strEmail) {
		$message->to($strEmail, $strEmail)->subject('Test Send Email From Goodtreefms');
	});

	if (count(Mail::failures()) > 0) {
		throw new Exception("Fail send email");
	} else {
		echo 'Send Email successfully to: ' . $strEmail;
	}
} catch (\Webup\LaravelSendinBlue\SendinBlueException $exc) {
	echo $exc->getMessage().": <br />";
}

![image](https://user-images.githubusercontent.com/9911699/57218201-50043800-7027-11e9-8a5d-b40d153a49ee.png)

help!
