### ISSUE TITLE
embed support

### ISSUE THREAD

**Issue by pehbehbeh** [agence-webup/laravel-sendinblue#14]
Hi, I could not get the `$message->embed(..)` helper to work with SendinBlue. The embedded image can not be displayed.

```html
<img width="50" height="50" align="center" alt="lorem ipsum" src="{{ $message->embed('/app/public/images/logo.png') }}">
```

The same code was working perfectly fine when using the Mailgun provider.

Do you know if CIDs are supported on SendinBlue or am I missing something?

**Comment by pehbehbeh** [comment]
`embedData` also does not work.

**Comment by Biptaste** [comment]
Hello, It seems that SendinBlue does not support CIDs. I plan to update to api v3 but it does not either.
