### ISSUE TITLE
Laravel 6 support ?

### ISSUE THREAD

**Issue by nnerijuss** [agence-webup/laravel-sendinblue#16]
When this package will be compatible with laravel 6 ?

**Comment by akgunumit** [comment]
+1

**Comment by mikycol** [comment]
+1

**Comment by robinparisi** [comment]
Hi,

We plan to do it soon but do not hesitate to propose a PR to go faster.

**Comment by marcbelletre** [comment]
Hi, I just created a PR for this (#17)

**Comment by Biptaste** [comment]
Thank you, I released the v1.1.5
