### ISSUE TITLE
Upgrade to V2 / custom headers 

### ISSUE THREAD

**Issue by paulhottinga** [agence-webup/laravel-sendinblue#18]
Hi,

Thanks for update to Sendinblue api V3. In version 1.1.* we are using custom Sendinblue headers for mail tracking. 

We add them in a Laravel mailable like:

`$this->withSwiftMessage(function ($message) {
      $headersTag = $message->getHeaders();
      $headersTag->addTextHeader('X-Mailin-Tag', ''.App::environment().'');
 });`

In version 2.0 the support for custom headers is removed?  In 2.0.* adding headers is removed?

`if ($message->getHeaders()) {
    $headers = $message->getHeaders()->getAll();
         foreach( $headers as $header) {
            if( $header instanceof Swift_Mime_Headers_UnstructuredHeader ) {
                $data['headers'][$header->getFieldName()] = $header->getValue();
           }
    }
}`

**Comment by Biptaste** [comment]
Hi, you right, I forgot it. You can use the v2.0.1

**Comment by paulhottinga** [comment]
Hi, tnx, super this quick addition!
