### ISSUE TITLE
Laravel 6.1 support

### ISSUE THREAD

**Issue by krns** [agence-webup/laravel-sendinblue#19]
To support https://github.com/laravel/framework/releases/tag/v6.1.0 please change the [`illuminate/mail` version](https://github.com/agence-webup/laravel-sendinblue/blob/master/composer.json#L15).

**Comment by pehbehbeh** [comment]
It think the constraints should be:

```
"illuminate/mail": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0",
```

...since Laravel 6 uses Semantic Versioning now.

**Comment by Biptaste** [comment]
You right, I don't know why I didn't use caret. I released [2.0.2](https://github.com/agence-webup/laravel-sendinblue/tree/v2.0.2)
