### ISSUE TITLE
TransactionEmail template with vars

### ISSUE THREAD

**Issue by petericebear** [agence-webup/laravel-sendinblue#25]
Hi,

How would you send a transactional email from a template with some variabels with this package?

Greeting,
Peter

**Comment by Biptaste** [comment]
Hi,

We can't use sendinblue's template with this package. It's not compliant with Laravel mail.

This package aims to handle sendinblue like other mail providers in laravel (Postmark, Mailgun...) to keep the same way to write mails.

**Comment by petericebear** [comment]
Hi, Oke thanks, thats clear!
