### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by SevymolSebastian** [agence-webup/laravel-sendinblue#27]
Trying to send emailusing sendinblue driver,

exception: "SendinBlue\Client\ApiException"
file: "\vendor\sendinblue\api-v3-sdk\lib\Api\SMTPApi.php"
line: 3986
message: "[0] cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"

Laravel: 6.18.15
webup/laravel-sendinblue: 2.0.3
sendinblue/api-v3-sdk: 6.3.0
PHP: 7.2.25
WAMP

**Comment by robinparisi** [comment]
Hi,

With current infos, this seems related to sendiblue. You can open an issue here:  https://github.com/sendinblue/APIv3-php-library
