### ISSUE TITLE
Tags Param Function

### ISSUE THREAD

**Issue by masbenx** [agence-webup/laravel-sendinblue#28]
I can't use tags param using swiftMessage Header callback..
cant you help me to implement the tags param on outgoing mail?

**Comment by Biptaste** [comment]
Hi,

Good idea, we can implement tags the same way as the Amazon SES driver

**Comment by oneart-dev** [comment]
7 months later. Still cant use full power of sendinblue because of poor integration with laravel.

**Comment by robinparisi** [comment]
At the moment we are not sure of the best way to implement templates and tags because the base class of Laravel doesn't allow it. 

Feel free to contribute if you have any idea.

**Comment by vorban** [comment]
After looking through some code, it seems like Laravel interfaces are not compatible with such features.

If you need to use tags, You will need to used the SendInBlue API Library on its own, without our wrapper.
