### ISSUE TITLE
Mailer [sendinblue] is not defined. 

### ISSUE THREAD

**Issue by kennyturner** [agence-webup/laravel-sendinblue#29]
Running latest Laravel 7.15.0
Added to several installs including brand new fresh version with php7.3, php7.4.4
Followed setup instructions for this package and when i go to send an email get the error "Mailer [sendinblue] is not defined"

Using a simple email script to test:
`\Mail::raw('hello world', function($message) { $message->subject('message subject')->to($email); });`

Thanks

**Comment by vahidalvandi** [comment]
https://laracasts.com/discuss/channels/laravel/laravel-7-replaced-mail-driver-by-mail-mailer

**Comment by turkishjoe** [comment]
It is not fixed yet.

Adding this line at config/mail.php(as mailers, like mailgun or smtp) helped me.

```
 'sendinblue'=>[
            'transport'=>'sendinblue'
 ],
```

It was hot fix.

**Comment by Biptaste** [comment]
Thanks, I edited the README

**Comment by turkishjoe** [comment]
@Biptaste good job gandalftux)
