### ISSUE TITLE
Unsuppoprted?

### ISSUE THREAD

**Issue by cardi777** [agence-webup/laravel-sendinblue#38]
I keep running into ...

```
InvalidArgumentException
Unsupported mail transport [sendinblue].
```
despite triple checking. I have tried it in Laravel 7.1 - 7.3

What am I dong wrong? Do I also need to install the SDK?

**Comment by SudoGetBeer** [comment]
From the README:

    config/services.php
```
    'sendinblue' => [
        // api-key or partner-key
        'key_identifier' => env('SENDINBLUE_KEY_IDENTIFIER', 'api-key'),
        'key' => env('SENDINBLUE_KEY'),
    ],
```

You need to add it there. Maybe check you local services.php against https://github.com/laravel/laravel/blob/8.x/config/services.php

**Comment by cardi777** [comment]
> From the README:
> 
> ```
> config/services.php
> ```
> 
> ```
>     'sendinblue' => [
>         // api-key or partner-key
>         'key_identifier' => env('SENDINBLUE_KEY_IDENTIFIER', 'api-key'),
>         'key' => env('SENDINBLUE_KEY'),
>     ],
> ```
> 
> You need to add it there. Maybe check you local services.php against https://github.com/laravel/laravel/blob/8.x/config/services.php

Yup its in there, perhaps its my versions?

```
"laravel/framework": "^7.30.1",
"webup/laravel-sendinblue": "^3.1"
```

Services.php has:

```
'sendinblue' => [
        // api-key or partner-key
        'key_identifier' => env('SENDINBLUE_KEY_IDENTIFIER', 'api-key'),
        'key'            => env('SENDINBLUE_KEY'),
],
```
And in mail.php:

```
'sendinblue' => [
'transport' => 'sendinblue',
],
```
.env

`MAIL_MAILER=sendinblue`

Full error & context

```
InvalidArgumentException
Unsupported mail transport [sendinblue].
```

```
public function createTransport(array $config)
    {
        // Here we will check if the "transport" key exists and if it doesn't we will
        // assume an application is still using the legacy mail configuration file
        // format and use the "mail.driver" configuration option instead for BC.
        $transport = $config['transport'] ?? $this->app['config']['mail.driver'];
 
        if (isset($this->customCreators[$transport])) {
            return call_user_func($this->customCreators[$transport], $config);
        }
 
        if (trim($transport) === '' || ! method_exists($this, $method = 'create'.ucfirst($transport).'Transport')) {
            throw new InvalidArgumentException("Unsupported mail transport [{$transport}].");
        }
 
        return $this->{$method}($config);
    }
```

**Comment by robinparisi** [comment]
Hi,

Could you please provide some code and more informations? Thanks!

**Comment by Malkom** [comment]
Hello,
I have the same problem and I don't know what is the `SENDINBLUE_KEY_IDENTIFIER` on my sendinblue desk.... I have juse un API Key and it's the `SENDINBLUE_KEY` on my .env

**Comment by cardi777** [comment]
> Hi,
> 
> Could you please provide some code and more informations? Thanks!

Thanks for the follow up!

Sorry to be a pain, I am not sure what more i can provide - I have settings for mail.php, services.php, composer.json, and the error message.

Let me know and I will give you whatever you think will help :)

**Comment by danilopolani** [comment]
I just tried to install this on a L8.x and it works fine. Maybe you disabled the [auto package discovery](https://laravel.com/docs/8.x/packages#package-discovery)? Can you try adding `\Webup\LaravelSendinBlue\SendinBlueServiceProvider::class` to `providers` array in your `config/app.php` file?

**Comment by cardi777** [comment]
> I just installed this on a L8.x and it works fine. Maybe you disabled the [auto package discovery](https://laravel.com/docs/8.x/packages#package-discovery)? Can you try adding `\Webup\LaravelSendinBlue\SendinBlueServiceProvider::class` to `providers` array in your `config/app.php` file?

thx - will give it a whirl and let you know
