### ISSUE TITLE
Class swift.transport does not exist 

### ISSUE THREAD

**Issue by funkydata** [agence-webup/laravel-sendinblue#4]
After a fresh install:

`composer require webup/laravel-sendinblue:1.0.0`

on an existing project [5.1.16 (LTS)] I get this error:

```
  [ReflectionException]                 
  Class swift.transport does not exist  
```

I have checked that in the providers list I have:

`Illuminate\Mail\MailServiceProvider::class`

which registers swift.transport on line 104:

```
    protected function registerSwiftTransport()
    {
        $this->app['swift.transport'] = $this->app->share(function ($app) {
            return new TransportManager($app);
        });
    }
```

Thank you for your help!

**Comment by funkydata** [comment]
It would seem that update to the latest laravel minor version fixes the issue.

Will keep you updated.

**Comment by Biptaste** [comment]
Thank you for this feedback. I close this issue.
