### ISSUE TITLE
how can send batch in one api request

### ISSUE THREAD

**Issue by vahidalvandi** [agence-webup/laravel-sendinblue#40]
hello , i need send batch email in one api request , sample : i have 1000 email with same text body ,

**Comment by vorban** [comment]
Currently, this library doesn't allow you to batch emails in a single API request.

Laravel allows you to specify several recipients, same goes for the SIB library. However, I do not know if the SwiftMail library all us to get back the list of recipients.
Furthermore, I do not know if the SIB api treats several recipients as several mails, or a single mail having multiple recipients, which may not be what you want.
