### ISSUE TITLE
do it support addContactToList	 method ??

### ISSUE THREAD

**Issue by vahidalvandi** [agence-webup/laravel-sendinblue#41]
in url

https://github.com/sendinblue/APIv3-php-library#documentation-for-api-endpoints

have multi methods how i can call them like 

**ContactsApi | addContactToList | POST /contacts/lists/{listId}/contacts/add**

**Comment by vorban** [comment]
Hello @vahidalvandi  !
Nope, this library doesn't support SendInBlue features that are outside the scope of Laravel Transporters, as specified in the [Readme.md](https://github.com/agence-webup/laravel-sendinblue#regarding-additional-features).

If you need to manipulate the ContactsApi of SendInBlue with endpoints like addContactToList, you should directly use the official PHP library (not Laravel specific).

You can install it:
```bash
composer require sendinblue/api-v3-sdk
```
Then you can do something like the following :
```php
$contactEmails = new AddContactToList([
    'emails' => [$email]
]);
try {
    $this->contactsApi->addContactToList($list_id, $contactEmails);
} catch (\Throwable $th) {
    Log::channel("sendinblue")->error($th->getMessage() . ' Error with sendinblueAPI while adding contact to list');
    throw $th;
}
```

This is a snippet that we currently use ourselves. Classes and methods are provided by the aforementioned library.
Further documentation can be found in the [Github repository](https://github.com/sendinblue/APIv3-php-library) of SendInBlue, alongside installation instructions.
