### ISSUE TITLE
Bug With guzzle 7.2+ laravel 8 + solution

### ISSUE THREAD

**Issue by neoteknic** [agence-webup/laravel-sendinblue#42]
**Describe the bug**
Error: Call to undefined function GuzzleHttp\Psr7\build_query() in /home/streamdeck/www/vendor/sendinblue/api-v3-sdk/lib/Api/TransactionalEmailsApi.php:5021

**To Reproduce**
Send an email

**Resolution**
Replace GuzzleHttp\Psr7\build_query() with GuzzleHttp\Psr7\Query::build()

**Comment by neoteknic** [comment]
juste upgrade sendinblue lib

**Comment by texit-dev** [comment]
I added "guzzlehttp/guzzle": "^6.2" to my composer.json. That solves the problem.

In GuzzleHttp\Psr7 Query::build() ist deprecated.

**Comment by Biptaste** [comment]
It's reported to sendinblue repo [PHP 8 and Guzzle 7.4 is not compatible with your latest version 7.4.3 #164](https://github.com/sendinblue/APIv3-php-library/issues/164)

**Comment by texit-dev** [comment]
fixed in 7.4.4 -> https://github.com/sendinblue/APIv3-php-library/releases/tag/v7.4.4

**Comment by Biptaste** [comment]
released in 3.2.0
