### ISSUE TITLE
Tags not save

### ISSUE THREAD

**Issue by FlorentJonville** [agence-webup/laravel-sendinblue#49]
Hi,

I'm not sure it's a bug, maybe I missed something ...
Tags are not registered on SendInBlue :(

Here is my code:

From my controller
```
...
    $email = new TestMail();
    $email->model  = $model;
    $email->subject = $subject;
    $email->recipient = request('email_test');
    $email->tags = ['tag_test'];

    Mail::mailer('sendinblue')
        ->to(request('email_test'))
        ->queue($email);
...
```

From App/Mail/TestMail.php
```
use SendinBlue;

public $theme = 'test';
...
public $tags;

    public function build()
    {
            return $this
            ->view([])
            ->replyTo($this->model->email_exp, $this->model->title)
            ->from('test@my-domain.com')
            ->markdown('emails.test')
            ->subject($this->subject)
            ->sendinblue(
                [
                    'tags' => [$this->tags],
                ]
            );
...
```

Everything is working fine and the email is sent correctly but the tags are not visible on the SendInBlue dashboard on "Transactional email> Logs"

![Capture d’écran 2021-11-09 à 15 17 35](https://user-images.githubusercontent.com/14126927/140940615-c4e0df39-708f-45b7-8b84-5332fbba2f91.png)

**Comment by boryn** [comment]
Hi @FlorentJonville!

I think you end up with a nested array `[['tag_test']]`. As you have `$email->tags = ['tag_test'];` probably you'll need:
```php
    ->sendinblue(
	[
	    'tags' => $this->tags,
	]
    );
```

**Comment by FlorentJonville** [comment]
Hi @boryn,
Thanks ! you're right and I fixed the error.
But the problem persists, even with :
`'tags' => ['offer'],`
It doesn't work

**Comment by boryn** [comment]
With my implementation the tags got saved in SendinBlue:
![image](https://user-images.githubusercontent.com/807297/140955706-44b60073-1325-46f6-ad8e-0bf777a38753.png)

Maybe let's try with even a simpler config, in the TestMail.php I have:
```php
public function build()
    {
        return $this
            ->view([])
            ->subject('subject')
            ->sendinblue(
                [
                    'tags' => ['tag1', 'tag2', 'test'],
                ]
            );
    }
```

and in the controller I use this syntax:
```php
$email = new TestMail();
Mail::to($to)->send($mail);
```

Which version of the library and Laravel do you use? The above works based on v2 branch of the library and on Laravel 6.x

**Comment by FlorentJonville** [comment]
Hello,

I remove Mail::mailer('sendinblue') and define, directly in my .env, sendinblue as default mailer

Now with 
`Mail::to($to)->send($mail);`

Tags are successfully save.

Thanks for your help ! ;-)

**Comment by vorban** [comment]
This seems resolved, closing the issue :)
