### ISSUE TITLE
Log template_id, tags and params if MAIL_DRIVER=log

### ISSUE THREAD

**Issue by chriswait** [agence-webup/laravel-sendinblue#53]
First, thanks for this fantastic library!

**Is your feature request related to a problem? Please describe.**
I'm migrating an existing Laravel app over to SendInBlue, and I'd love an easy way to test my new Mailables are correct without using up my SendInBlue quota.

Also, in test environments, I'd like to log emails instead of actually sending them (so I can test e.g password reset links, without accidentally sending emails)

**Describe the solution you'd like**
When MAIL_DRIVER=log, the SendInBlue trait's `sendinblue()` method would output the template_id, tags and params to the laravel.log. (Currently it writes the standard mail headers, but not the `sendinblue/x-extra-fields` headers)

**Describe alternatives you've considered**

- creating a `views.email.debug` email view to use in place of `view([])`, which attempts renders all passed params but only if MAIL_DRIVER=log, otherwise it renders nothing. Seems suboptimal to repeat this for each project.

**Additional context**
**I'd be happy to have a go at putting together PRs for this** for v2 and v3 with some support.

I think the if-statement [here](https://github.com/agence-webup/laravel-sendinblue/blob/master/src/SendinBlue.php#L16) changes to something like:
`if ($this instanceof Mailable && ($this->mailDriver() == "sendinblue" || $this->mailDriver() == "log")) {`

This seems to result in the following being logged (and no emails actually being sent, presumably because `withSwiftMessage` also respects MAIL_DRIVER?):
```
[2022-02-02 19:16:34] local.DEBUG: Message-ID: <347e53cc53156ed76ca1afb7246c16c8@swift.generated>
Date: Wed, 02 Feb 2022 19:16:34 +0000
Subject: ___TEMPLATE_SUBJECT___
From: [sender name and email]
To: [my email]
MIME-Version: 1.0
Content-Type: multipart/related;
 boundary="_=_swift_1643829394_87130599fa05b0c0a29b57063a21e137_=_"

Content-Type: application/octet-stream; name="sendinblue/x-extra-fields"
Content-Transfer-Encoding: base64
Content-ID: <f3cce0f3b7d1c72a8dfc03326273676a@swift.generated>
Content-Disposition: inline; filename="sendinblue/x-extra-fields"

{"template_id":123,"tags":[],"params":{"foo":"Bar"}}  
```

Which seems ideal.

**Comment by Biptaste** [comment]
Hello, thanks for your feedback. It's a good idea. I don't think MAIL_DRIVER aims to define a log mode. But we can add MAIL_SENDINBLUE_LOG and may be with options to only write logs or to send mail and write logs @vorban

**Comment by chriswait** [comment]
The log mode is actually a documented feature - Laravel suggests setting `MAIL_MAILER=log` for the following behaviour:

>Instead of sending your emails, the log mail driver will write all email messages to your log files for inspection. Typically, this driver would only be used during local development. 

https://laravel.com/docs/8.x/mail#log-driver

If you add a new .env variable called `MAIL_SENDINBLUE_LOG` and leave MAIL_DRIVER=sendinblue, I think there's a risk that the `withSwiftMessage` function would actually send emails...

**Comment by Biptaste** [comment]
Oh Nice, I didn't know. Go for `MAIL_DRIVER=log`

**Comment by chriswait** [comment]
Awesome. I've put together an extremely small PR which implements this change. If you're happy with it, I have another one ready to go for the v2 branch (which is what my project uses as it's still on Laravel 6)
