### ISSUE TITLE
textContent is missing!

### ISSUE THREAD

**Issue by vaskomichal** [agence-webup/laravel-sendinblue#57]
Hi, I have a problem with sending a email,
When I try to send a email I got exception SendinBlue\Client\ApiException
[400] Client error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `400 Bad Request` response: {"code":"missing_parameter","message":"textContent is missing"}

Here is my email build function. 

`public function build()
    {
        return $this
            ->view([])
            ->subject(SendinBlueTransport::USE_TEMPLATE_SUBJECT) // use template subject
            // ->subject('My own subject') // subject overridden
            ->sendinblue(
                [
                    'template_id' => 1,
                    'tags'        => ['offer'],
                    'params'      => [
                        'FIRSTNAME' => 'John',
                        'AMOUNT'    => '29',
                    ],
                ]
            );
    }`

And here is a route where I try to test sending email

`Route::get('/test', function () {
    $user = Auth::user();
    Mail::mailer('sendinblue')->to($user->email)->send(new \App\Mail\TestEmail());
});`

Thanks!

**Comment by boryn** [comment]
Hi! Not sure if this could help, but first try to build the TestEmail:
`$mail = new \App\Mail\TestEmail();`

and later send with `Mail::to($user->email)->send($mail);`.

The other thing is whether you really have template of id 1? Check if you have FIRSTNAME and AMOUNT params used in the template. Or maybe you use some parameters in template which are missing and not defined here in the code? Sendinblue is very sensitive about this.

**Comment by vorban** [comment]
@vaskomichal  As far as I know [this the line](https://github.com/agence-webup/laravel-sendinblue/blob/c38fc39b1db4cf0f144ca838d8d8ed62fefd75da/src/SendinBlueTransport.php#L217) that takes care of this specific error.
It was introduced in [this commit](https://github.com/agence-webup/laravel-sendinblue/commit/0669ca1df3769f1fe4cc462d5f20a3c09e6550f7) by @boryn .

Could you please make sure that you are up to date with the latest release available?

**Comment by mihaidgag** [comment]
@vorban same happens to me, usin 3.5.0 version of the package and i checked to see that the code is there but first of all using: 
"->subject(SendinBlueTransport::USE_TEMPLATE_SUBJECT)"
causes missing parameter: subject is required
and if i put my own subject then: textContent is missing
