### ISSUE TITLE
Add methode pin() for compatibility failover on Laravel 8

### ISSUE THREAD

**Issue by pcomble** [agence-webup/laravel-sendinblue#59]
Laravel 8 introduce Failover Configuration : https://laravel.com/docs/8.x/mail#failover-configuration

For compatibility, it's necessary override method \Illuminate\Mail\Transport\Transport::ping() in class \Webup\LaravelSendinBlue\SendinBlueTransport for check accessibility of sendinblue API.

**Comment by Biptaste** [comment]
I merged your PR https://github.com/agence-webup/laravel-sendinblue/pull/60
Thank you
